Repository GoldKing9/AirbnbClone_backend, pull requests merged in 2023-08, with the labels that each got.

#11 [Feat] review api 개발 #3
  airbnbClone/.gitignore
  airbnbClone/build.gradle
  airbnbClone/src/main/java/dbDive/airbnbClone/AirbnbCloneApplication.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/service/ReservationService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/controller/ReviewController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/dto/request/ReviewRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/dto/response/ReviewComment.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/dto/response/ReviewModifyResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/dto/response/ReviewResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/service/ReviewService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/controller/UserController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/response/UserReviewResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/response/UserReviews.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/service/UserService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/accommodation/Accommodation.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/accommodation/AcmdImage.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/resevation/Reservation.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/review/Review.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/review/ReviewRepository.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/review/ReviewRepositoryCustom.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/review/ReviewRepositoryImpl.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepository.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepositoryCustom.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepositoryImpl.java
  airbnbClone/src/test/java/dbDive/airbnbClone/api/review/controller/ReviewControllerTest.java
  airbnbClone/src/test/java/dbDive/airbnbClone/api/user/controller/UserControllerTest.java
Labels: 백엔드_구현, 최하록

#9 Feat acmd search & view
  airbnbClone/.gitignore
  airbnbClone/src/main/java/dbDive/airbnbClone/AirbnbCloneApplication.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/controller/AccommodationController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/dto/AccommodationDataDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/dto/ImageDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/dto/request/SearchRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/dto/response/DetailAcmdResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/dto/response/SearchResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/service/AccommodationService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/accommodation/Accommodation.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/accommodation/AcmdImage.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/resevation/Reservation.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/review/Review.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/accommodation/AccommodationRepository.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/accommodation/AccommodationRepositoryCustom.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/accommodation/AccommodationRepositoryImpl.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepository.java
  airbnbClone/src/main/resources/data.sql
  airbnbClone/src/test/java/dbDive/airbnbClone/repository/accommodation/AccommodationRepositoryTest.java
Labels: 백엔드_구현, 정상준

#12 [Feat] 10조 유저 회원가입 API 구현 #4
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/controller/UserController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/request/SignupReq.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/service/UserService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/Appconfig.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/SecurityConfig.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/user/User.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepository.java
Labels: 권판준, 백엔드_구현

#13 Feat user
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/controller/UserController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/request/SignupReq.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/service/UserService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/Appconfig.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/SecurityConfig.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/user/User.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepository.java
Labels: 권판준, 백엔드_구현

#15 [Feat] User profile API 구현 #14
  airbnbClone/build.gradle
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/dto/response/ReviewComment.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/controller/UserController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/request/ModifyUserProfileRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/response/UserProfileAcmd.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/response/UserProfileResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/service/UserService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/user/User.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepositoryCustom.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepositoryImpl.java
  airbnbClone/src/main/resources/data.sql
  airbnbClone/src/test/java/dbDive/airbnbClone/api/user/controller/UserControllerTest.java
Labels: 백엔드_구현, 최하록

#17 [FEAT] 예약 API 구현 #16
  airbnbClone/.gitignore
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/controller/ReservationController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/HostReservationDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/ReservationDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/SelectReservationDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/request/BookRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/response/HostTotalAccommodationResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/response/SelectAccommodationResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/response/TotalAccommodationResponse.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/service/ReservationService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/resevation/Reservation.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepository.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepositoryCustom.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepositoryImpl.java
Labels: 고예진, 도와주세요!!, 백엔드_구현

#24 [Feat] 10조 CSRF 설정 추가
  airbnbClone/src/main/java/dbDive/airbnbClone/config/auth/SecurityConfig.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/utils/JwtUtils.java
Labels: 권판준, 백엔드_구현

#25 [refactor] AuthUser 반영
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/controller/ReviewController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/dto/request/ReviewRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/review/service/ReviewService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/controller/UserController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/service/UserService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/utils/JwtProperties.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/review/Review.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepositoryImpl.java
Labels: 리팩토링, 최하록

#27 refator : AuthUser 반영 #26
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/controller/ReservationController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/service/ReservationService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/utils/JwtProperties.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepositoryCustom.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepositoryImpl.java
Labels: 고예진, 리팩토링

#28 refactor : AuthUser 반영
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/controller/AccommodationController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/accommodation/service/AccommodationService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/controller/ReservationController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/config/utils/JwtProperties.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/accommodation/Accommodation.java
Labels: 리팩토링, 이수민

#33 [Fix] login 설정 수정 #32
  airbnbClone/src/main/java/dbDive/airbnbClone/config/SecurityConfig.java
Labels: 권판준, 백엔드_구현

#35 feat : 숙박 예약 인원 설정 #34
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/service/ReservationService.java
Labels: 고예진, 백엔드_구현

#39 feat : 게스트 숙소 예약 status 추가 #38
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/response/ReservationDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/reservation/dto/response/SelectReservationDto.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/reservation/ReservationRepositoryImpl.java
Labels: 고예진, 백엔드_구현

#41 feat : 아이디/비밀번호 찾는 API 추가 #40
  airbnbClone/build.gradle
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/controller/UserFindController.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/request/ChangePasswordRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/request/FindEmailRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/dto/request/FindPasswordRequest.java
  airbnbClone/src/main/java/dbDive/airbnbClone/api/user/service/UserFindService.java
  airbnbClone/src/main/java/dbDive/airbnbClone/entity/user/User.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepository.java
  airbnbClone/src/main/java/dbDive/airbnbClone/repository/user/UserRepositoryImpl.java
Labels: 고예진, 백엔드_구현
